/**
 * 表单属性工厂
 * @return {[object]} 属性对象
 */
define(function(){
  var formOptionMap={
    "form":{
      editOption:{
            method:{
              title:"method",
              el:"select",
              notNull:true,
              defaultVal:{
                get:"get",
                post:"post"
              }
            },
            action:{
              title:"action",
              el:"input",
              notNull:true
            },
            enctype:{
              title:"enctype",
              el:"select",
              notNull:true,
              defaultVal:{
                "application/x-www-form-urlencoded":"application/x-www-form-urlencoded",
                "multipart/form-data":"multipart/form-data",
                "text/plain":"text/plain"
              }
            }
      }
    },
    "label":{
      editOption:{
        html:{
          title:"标题内容",
          el:"input",
          type:"text"
        }
      }
    },
    "input":{
      editOption:{
        name:{
          title:"name",
          el:"input",
          notNull:true,
        },
        placeholder:{
          title:"placeholder",
          el:"input"
        },
        type:{
          title:"type",
          el:"select",
          defaultVal:{
            text:"text",
            email:"email",
            number:"number",
            tel:"tel"
          }
        }
      }
    },
    "checkbox":{
      editOption:{
        value:{
          title:"value",
          el:"input",
          notNull:true
        },
        name:{
          title:"name",
          el:"input",
          notNull:true
        },
        checked:{
          title:"checked",
          el:"checkbox"
        }
      }
    },
    "select":{
        editOption:{
          name:{
            title:"name",
            el:"input",
            notNull:true
          }
        }
    },
    "radio":{
      editOption:{
        value:{
          title:"value",
          el:"input",
          notNull:true
        },
        name:{
          title:"name",
          el:"input",
          notNull:true
        },
        checked:{
          title:"checked",
          el:"checkbox"
        }
      }
    },
    "file":{
      editOption:{
        name:{
          title:"name",
          el:"input",
          notNull:true
        },
        postUrl:{
          title:"postUrl",
          el:"input"
        },
        postType:{
          title:"postType",
          el:"select",
          defaultVal:{
            "get":"get",
            "post":"post"
          }
        }
      }
    },
    "multiline":{
      editOption:{
        name:{
          title:"name",
          el:"input",
          notNull:true
        }
      }
    }





  }


  return formOptionMap;
});
